In [1]:
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.__version__

'1.16.4'

In [2]:
print(iris)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

In [3]:
##1 Извлечь колонку ‘species’. 2 Преобразовать первые 4 колонки в 2D массив

b = np.array(iris[:,0:4])
print(b)

[[b'5.1' b'3.5' b'1.4' b'0.2']
 [b'4.9' b'3.0' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.3' b'0.2']
 [b'4.6' b'3.1' b'1.5' b'0.2']
 [b'5.0' b'3.6' b'1.4' b'0.2']
 [b'5.4' b'3.9' b'1.7' b'0.4']
 [b'4.6' b'3.4' b'1.4' b'0.3']
 [b'5.0' b'3.4' b'1.5' b'0.2']
 [b'4.4' b'2.9' b'1.4' b'0.2']
 [b'4.9' b'3.1' b'1.5' b'0.1']
 [b'5.4' b'3.7' b'1.5' b'0.2']
 [b'4.8' b'3.4' b'1.6' b'0.2']
 [b'4.8' b'3.0' b'1.4' b'0.1']
 [b'4.3' b'3.0' b'1.1' b'0.1']
 [b'5.8' b'4.0' b'1.2' b'0.2']
 [b'5.7' b'4.4' b'1.5' b'0.4']
 [b'5.4' b'3.9' b'1.3' b'0.4']
 [b'5.1' b'3.5' b'1.4' b'0.3']
 [b'5.7' b'3.8' b'1.7' b'0.3']
 [b'5.1' b'3.8' b'1.5' b'0.3']
 [b'5.4' b'3.4' b'1.7' b'0.2']
 [b'5.1' b'3.7' b'1.5' b'0.4']
 [b'4.6' b'3.6' b'1.0' b'0.2']
 [b'5.1' b'3.3' b'1.7' b'0.5']
 [b'4.8' b'3.4' b'1.9' b'0.2']
 [b'5.0' b'3.0' b'1.6' b'0.2']
 [b'5.0' b'3.4' b'1.6' b'0.4']
 [b'5.2' b'3.5' b'1.5' b'0.2']
 [b'5.2' b'3.4' b'1.4' b'0.2']
 [b'4.7' b'3.2' b'1.6' b'0.2']
 [b'4.8' b'3.1' b'1.6' b'0.2']
 [b'5.4' b'3.4' b'1.5' b'0.4']
 [b'5.2'

In [4]:
## 3 Посчитать mean, median, standard deviation по 1-й колонке
b = np.array(b, dtype='float')

print("Mean value is: ", b[:, 0:1].mean())
print("Mean value is: ", np.mean(b[:, 0:1]))

Mean value is:  5.843333333333334
Mean value is:  5.843333333333334


In [5]:
print("Median value is: ", np.median(b[:, 0:1]))

Median value is:  5.8


In [6]:
print("Mean standard deviation is: ", b[:, 0:1].std())

Mean standard deviation is:  0.8253012917851409


In [7]:
## 4 Вставить 20 значений np.nan на случайные позиции в массиве

np.put(b, np.random.choice(range(150*4), 20, replace=False), np.nan)
print(b)
b.dtype.name

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 nan]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [nan 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 nan 0.4]
 [5.1 3.5 1.4 0.3]
 [nan 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 nan 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 nan 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [nan 3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

'float64'

In [8]:
 ### 5 Найти позиции вставленных значений np.nan в 1-й колонке
c = np.array((b[:,0:1]), dtype='float64')
np.where(np.isnan(c))

(array([  9,  18,  49,  54,  65,  87, 108], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [9]:
## 6 Отфильтровать массив по условию значения в 3-й колонке > 1.5 и значения в 1-й колонке < 5.0
more1_5 = np.where(b[:,3] > 1.5)
print("Positions where value > 1.5: ", more1_5)

Positions where value > 1.5:  (array([ 56,  70,  77,  83,  85, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 120, 121,
       122, 124, 125, 126, 127, 128, 129, 130, 131, 132, 135, 136, 137,
       138, 139, 140, 141, 143, 144, 145, 146, 147, 148, 149], dtype=int64),)


C:\Users\Olya\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


In [10]:
less_5 = np.where(b[:,1] < 5)
print("Positions where value < 5: ", less_5)

Positions where value < 5:  (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
       121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
       134, 136, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
       149], dtype=int64),)


C:\Users\Olya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


In [11]:
## 7 Заменить все значения np.nan на 0
missing_bool = np.isnan(b) | np.isinf(b)
b[missing_bool] = 0 
print(b)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0. ]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [0.  3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [0.  3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 0.  1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 0.  0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [0.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
### 8 Посчитать все уникальные значения в массиве и вывести их вместе с подсчитанным количеством
uniqs, counts = np.unique(b, return_counts=True)
print("Unique items : ", uniqs)
print("\n")
print("Counts       : ", counts)

Unique items :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]


Counts       :  [20  6 27  7  7  1  1  8  4  7 19 20 25 11  6 11  6  7  6  5 12  6 10  5
  8 14 10 26 11 13  8 11  8  4  4  7  5  6  4  5  3  8  9  7  7  9  9 13
 17  6  3  8  9 12 10 10  5  8  9  4  9  8  4  3  8  3  5  1  1  3  1  1
  1  4  1]


In [13]:
## 9. Разбить массив по горизонтали на 2 массива
b2 = np.array_split(b,2)
print(b2)
np.array


[array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0. ],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [0. , 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 0. , 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 0. , 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 0. , 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 

<function numpy.array>

In [14]:
b_1 = np.array(b[0:76,:])
print(b_1)
b_2 = np.array(b[76:,:])
print(b_2)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0. ]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [0.  3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [0.  3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 0.  1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 0.  0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [0.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [15]:
##10 Отсортировать оба получившихся массива по 1-й колонке: 1-й по возрастанию, 2-й по убывани.
sorted_index_1stcol = b_1[:, 0].argsort()
print(b_1[sorted_index_1stcol])


[[0.  3.8 1.7 0.3]
 [0.  3.3 1.4 0.2]
 [0.  2.8 4.6 1.5]
 [0.  3.1 4.4 1.4]
 [0.  3.1 1.5 0.1]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.  1.4 0. ]
 [5.  3.5 1.6 0.6]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  2.  3.5 1. ]
 [5.  3.4 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.6 0.2]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 1.5 0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 3.5 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.4 0.  0.4]
 [5.4 0.  1.7 0.2]
 [5.4 3.9 0.  0.4]
 [5.4 3.9 1.7 0.4]
 [5.5 2.3 4.  1.3]
 [5.5 4.2 1.

In [16]:
sorted_index_2stcol = b_2[:, 0].argsort()
print(b_2[sorted_index_2stcol[::-1]])

[[7.9 3.8 6.4 2. ]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [7.7 2.8 6.7 2. ]
 [7.7 0.  6.1 2.3]
 [7.6 3.  6.6 2.1]
 [7.4 2.8 6.1 1.9]
 [7.3 2.9 6.3 1.8]
 [7.2 3.6 6.1 2.5]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [7.1 3.  5.9 2.1]
 [6.9 3.1 5.1 2.3]
 [6.9 3.2 5.7 2.3]
 [6.9 3.1 5.4 2.1]
 [6.8 3.  0.  2.1]
 [6.8 2.8 4.8 1.4]
 [6.8 3.2 5.9 2.3]
 [6.7 3.  5.  1.7]
 [6.7 3.1 4.7 1.5]
 [6.7 3.  5.2 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.3 5.7 2.1]
 [6.7 3.1 5.6 2.4]
 [6.5 3.  5.8 2.2]
 [6.5 3.  5.2 2. ]
 [6.5 3.2 5.1 2. ]
 [6.5 3.  5.5 1.8]
 [6.4 2.7 5.3 1.9]
 [6.4 3.2 5.3 2.3]
 [6.4 2.8 5.6 2.2]
 [6.4 0.  5.5 1.8]
 [6.4 2.8 5.6 2.1]
 [6.3 3.3 6.  2.5]
 [6.3 2.9 5.6 1.8]
 [6.3 2.8 5.1 1.5]
 [6.3 2.5 5.  1.9]
 [6.3 3.4 5.6 2.4]
 [6.3 2.7 4.9 0. ]
 [6.2 2.9 4.3 1.3]
 [6.2 3.4 5.4 2.3]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.1 2.6 5.6 1.4]
 [6.1 3.  4.6 1.4]
 [6.  2.2 5.  1.5]
 [6.  3.4 4.5 1.6]
 [6.  2.7 5.1 1.6]
 [6.  2.9 4.5 1.5]
 [6.  3.  4.8 1.8]
 [5.9 3.  5.1 1.8]
 [5.8 2.7 5.1 0. ]
 [5.8 2.6 4.

In [17]:
##11 Склеить оба массива обратно
b = np.vstack((b_1,b_2))
print(b)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0. ]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [0.  3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [0.  3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 0.  1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 0.  0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [0.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [18]:
##12 Найти наиболее часто повторяющееся значение в массиве

uniqs, counts = np.unique(b, return_counts=True)
print(uniqs[np.argmax(counts)])


0.2


In [19]:
 ###13 Написать функцию, которая бы умножала все значения в колонке,  меньше среднего значения в этой колонке, на 2, и делила остальные значения на 4. Применить к 3-й колонке

b_сolomn_3 = np.array(b[:,2], dtype=float)

x = np.sum(b_сolomn_3)/150
x 
cs = np.where(b_сolomn_3 < x, b_сolomn_3*2, b_сolomn_3/4)

print(cs)


[2.8   2.8   2.6   3.    2.8   3.4   2.8   3.    2.8   3.    3.    3.2
 2.8   2.2   2.4   3.    0.    2.8   3.4   3.    3.4   3.    2.    3.4
 3.8   3.2   3.2   3.    2.8   3.2   3.2   0.    3.    2.8   3.    2.4
 2.6   3.    2.6   3.    2.6   2.6   2.6   3.2   3.8   2.8   3.2   2.8
 3.    2.8   1.175 1.125 1.225 1.    1.15  1.125 1.175 6.6   1.15  0.975
 7.    1.05  1.    1.175 7.2   1.1   1.125 1.025 1.125 0.975 1.2   1.
 1.225 1.175 1.075 1.1   1.2   1.25  1.125 7.    0.95  0.925 0.975 1.275
 1.125 1.125 1.175 1.1   1.025 1.    1.1   1.15  1.    6.6   1.05  1.05
 1.05  1.075 6.    1.025 1.5   1.275 1.475 1.4   1.45  1.65  1.125 1.575
 1.45  1.525 1.275 1.325 0.    1.25  1.275 1.325 1.375 1.675 1.725 1.25
 1.425 0.    1.675 1.225 1.425 1.5   1.2   1.225 1.4   1.45  1.525 1.6
 1.4   1.275 1.4   1.525 1.4   1.375 1.2   1.35  1.4   1.275 1.275 1.475
 1.425 1.3   1.25  1.3   1.35  1.275]
